title: Linux friendly Manual
description: man-сторінки служать радше довідником для тих, хто вже знає, що шукає, а не підручником для новачків. Вони докладно описують, що робить кожна опція, але не завжди пояснюють як використовувати їх разом для вирішення реальних завдань.
